// <auto-generated />
namespace IT16A1.TestOnline.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class intialDb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(intialDb));
        
        string IMigrationMetadata.Id
        {
            get { return "201809080828114_intialDb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
